import copy
import hashlib
import json
from pathlib import Path

import jsonschema
import pytest

from authorship.sourcegraph_discovery import (
    evidence_packet_sha256,
    specification_sha256,
    validate_evidence_packet,
)
from authorship.sourcegraph_discovery_execution import (
    discovery_unit_id,
    result_manifest_sha256,
)
from authorship.sourcegraph_evidence_pipeline import (
    EvidencePipelineError,
    build_packet_index,
    packet_index_sha256,
    validate_packet_index,
)

SHA_A = "a" * 40
SHA_B = "b" * 40
SHA_C = "c" * 40
SOURCEGRAPH_NAME = "github.com/sg-evals/org-repo"
CANONICAL_ID = "org/repo"
CANONICAL_URL = "https://github.com/org/repo"


@pytest.fixture
def specification() -> dict:
    path = Path(__file__).resolve().parents[1] / "study/sourcegraph-discovery.v3.json"
    return json.loads(path.read_text())


@pytest.fixture
def index_manifest() -> dict:
    return {
        "repositories": [
            {
                "canonical_repository_id": CANONICAL_ID,
                "canonical_source_url": CANONICAL_URL,
                "cutoff_commit": SHA_A,
            }
        ]
    }


def canonical_hash(value: object) -> str:
    payload = json.dumps(
        value, ensure_ascii=False, separators=(",", ":"), sort_keys=True
    ).encode()
    return hashlib.sha256(payload).hexdigest()


def commit_result(*, diff: bool = False) -> dict:
    return {
        "__typename": "CommitSearchResult",
        "messagePreview": {
            "value": "Generated-by: Codex",
            "highlights": [],
        },
        "diffPreview": (
            {"value": "+ generated by Codex", "highlights": []} if diff else None
        ),
        "commit": {
            "repository": {"name": SOURCEGRAPH_NAME},
            "oid": SHA_B,
            "url": f"/org-repo/-/commit/{SHA_B}",
            "subject": "Generated-by: Codex",
            "author": {
                "date": "2025-03-01T12:00:00Z",
                "person": {
                    "name": "Agent Author",
                    "email": "agent@example.com",
                    "displayName": "Agent Author",
                },
            },
            "committer": {
                "date": "2025-03-02T12:00:00Z",
                "person": {
                    "name": "Agent Committer",
                    "email": "committer@example.com",
                    "displayName": "Agent Committer",
                },
            },
        },
    }


def file_result() -> dict:
    return {
        "__typename": "FileMatch",
        "repository": {"name": SOURCEGRAPH_NAME, "url": "/org-repo"},
        "file": {
            "name": "POLICY.md",
            "path": "docs/POLICY.md",
            "url": f"/org-repo/-/blob/{SHA_A}/docs/POLICY.md",
            "commit": {"oid": SHA_A},
        },
        "lineMatches": [
            {
                "preview": "AI-generated contributions are prohibited.",
                "lineNumber": 4,
                "offsetAndLengths": [[0, 12]],
                "limitHit": False,
            },
            {
                "preview": "Do not submit LLM generated code.",
                "lineNumber": 8,
                "offsetAndLengths": [[14, 3]],
                "limitHit": False,
            },
        ],
    }


def shard(specification: dict, family_id: str, raw_results: list[dict]) -> dict:
    family = next(
        family
        for family in specification["query_families"]
        if family["id"] == family_id
    )
    query = (
        family["query_template"]
        .replace("{sourcegraph_repo_regex}", r"github\.com/sg-evals/org-repo")
        .replace("{cutoff_commit}", SHA_A)
    )
    records = [
        {
            "sourcegraph_result_id": f"sha256:{canonical_hash(raw)}",
            "payload": raw,
        }
        for raw in raw_results
    ]
    records.sort(key=lambda record: record["sourcegraph_result_id"])
    document = {
        "result_manifest_version": 3,
        "query_family_id": family_id,
        "result_type": family["result_type"],
        "canonical_repository_id": CANONICAL_ID,
        "sourcegraph_name": SOURCEGRAPH_NAME,
        "cutoff_commit": SHA_A,
        "rendered_query": query,
        "rendered_query_sha256": hashlib.sha256(query.encode()).hexdigest(),
        "unit_id": "d" * 64,
        "executed_at": "2026-07-27T20:45:00Z",
        "sourcegraph_result_ids": [
            record["sourcegraph_result_id"] for record in records
        ],
        "result_count": len(records),
        "result_object_count": len(records),
        "limit_hit": False,
        "cloning_repositories": [],
        "missing_repositories": [],
        "timed_out_repositories": [],
        "valid": True,
        "invalid_reasons": [],
        "raw_results": records,
        "outcomes_consulted": False,
    }
    return {
        **document,
        "result_manifest_sha256": result_manifest_sha256(document),
    }


def file_enrichment(result_shard: dict) -> dict:
    result_id = result_shard["sourcegraph_result_ids"][0]
    return {
        "result_manifest_sha256": result_shard["result_manifest_sha256"],
        "sourcegraph_result_id": result_id,
        "indexed_revision_oid": SHA_A,
        "default_branch_reachable": True,
        "lines": [
            {
                "line": 4,
                "commit_oid": SHA_B,
                "observed_at": "2025-04-01T00:00:00Z",
            },
            {
                "line": 8,
                "commit_oid": SHA_C,
                "observed_at": "2025-05-01T00:00:00Z",
            },
        ],
    }


@pytest.mark.parametrize(
    ("family_id", "expected_kind"),
    [
        ("agent_trailer_commits", "commit_message"),
        ("recognized_agent_identity_commits", "commit_identity"),
        ("generated_code_disclosure_diffs", "diff_added"),
        ("ai_ban_policy_introduction_diffs", "diff_added"),
    ],
)
def test_commit_and_diff_results_become_raw_fact_packets(
    specification: dict,
    index_manifest: dict,
    family_id: str,
    expected_kind: str,
):
    result_shard = shard(
        specification,
        family_id,
        [commit_result(diff=family_id.endswith("_diffs"))],
    )

    packet_index = build_packet_index(
        specification,
        index_manifest,
        [result_shard],
        file_blame_enrichments=[],
    )

    assert packet_index["packet_count"] == 1
    assert packet_index["pending_file_enrichment_count"] == 0
    packet = packet_index["packets"][0]
    assert packet["raw_evidence"][0]["kind"] == expected_kind
    assert packet["candidate_event"] == {
        "commit_oid": SHA_B,
        "observed_at": "2025-03-02T12:00:00Z",
    }
    assert packet["packet_sha256"] == evidence_packet_sha256(packet)
    assert validate_evidence_packet(packet, specification) == []
    assert not ({"decision", "adoption_status", "policy_status"} & packet.keys())


def test_file_results_require_blame_and_split_by_introducing_commit(
    specification: dict,
    index_manifest: dict,
):
    result_shard = shard(specification, "ai_ban_policy_files", [file_result()])

    pending = build_packet_index(
        specification,
        index_manifest,
        [result_shard],
        file_blame_enrichments=[],
    )
    complete = build_packet_index(
        specification,
        index_manifest,
        [result_shard],
        file_blame_enrichments=[file_enrichment(result_shard)],
    )

    assert pending["packet_count"] == 0
    assert pending["pending_file_enrichment_count"] == 1
    assert complete["packet_count"] == 2
    assert complete["pending_file_enrichment_count"] == 0
    assert [
        packet["candidate_event"]["commit_oid"] for packet in complete["packets"]
    ] == [SHA_B, SHA_C]
    for packet in complete["packets"]:
        assert [evidence["kind"] for evidence in packet["raw_evidence"]] == [
            "file_content",
            "blame",
        ]
        assert validate_evidence_packet(packet, specification) == []


def test_path_only_file_match_closes_without_fabricating_blame_evidence(
    specification: dict,
    index_manifest: dict,
):
    result = file_result()
    result["lineMatches"] = []
    result_shard = shard(specification, "ai_ban_policy_files", [result])
    enrichment = {
        "result_manifest_sha256": result_shard["result_manifest_sha256"],
        "sourcegraph_result_id": result_shard["sourcegraph_result_ids"][0],
        "indexed_revision_oid": SHA_A,
        "default_branch_reachable": True,
        "lines": [],
    }

    packet_index = build_packet_index(
        specification,
        index_manifest,
        [result_shard],
        file_blame_enrichments=[enrichment],
    )

    assert packet_index["packet_count"] == 0
    assert packet_index["pending_file_enrichment_count"] == 0
    schema_path = (
        Path(__file__).resolve().parents[1]
        / "study/sourcegraph-file-blame-enrichment.schema.json"
    )
    jsonschema.Draft202012Validator(json.loads(schema_path.read_text())).validate(
        enrichment
    )


def test_unused_file_enrichment_is_rejected(
    specification: dict,
    index_manifest: dict,
):
    result_shard = shard(specification, "ai_ban_policy_files", [file_result()])
    unused = file_enrichment(result_shard)
    unused["sourcegraph_result_id"] = "sha256:" + "f" * 64

    with pytest.raises(EvidencePipelineError, match="unused file blame enrichment"):
        build_packet_index(
            specification,
            index_manifest,
            [result_shard],
            file_blame_enrichments=[unused],
        )


def test_file_enrichment_line_numbers_reject_booleans(
    specification: dict,
    index_manifest: dict,
):
    result_shard = shard(specification, "ai_ban_policy_files", [file_result()])
    enrichment = file_enrichment(result_shard)
    enrichment["lines"][0]["line"] = True

    with pytest.raises(
        EvidencePipelineError, match="enrichment line numbers must be integers"
    ):
        build_packet_index(
            specification,
            index_manifest,
            [result_shard],
            file_blame_enrichments=[enrichment],
        )


def test_non_github_sources_do_not_receive_fabricated_deep_links(
    specification: dict,
    index_manifest: dict,
):
    result_shard = shard(specification, "agent_trailer_commits", [commit_result()])
    index_manifest["repositories"][0][
        "canonical_source_url"
    ] = "https://codeberg.org/org/repo"

    packet_index = build_packet_index(
        specification,
        index_manifest,
        [result_shard],
        file_blame_enrichments=[],
    )

    assert (
        packet_index["packets"][0]["raw_evidence"][0]["source_url"]
        == "https://codeberg.org/org/repo"
    )


def test_zero_results_are_retained_as_sources_but_create_no_packets(
    specification: dict,
    index_manifest: dict,
):
    empty = shard(specification, "agent_trailer_commits", [])

    packet_index = build_packet_index(
        specification,
        index_manifest,
        [empty],
        file_blame_enrichments=[],
    )

    assert packet_index["packet_count"] == 0
    assert packet_index["source_result_manifest_sha256s"] == [
        empty["result_manifest_sha256"]
    ]
    assert validate_packet_index(packet_index, specification) == []


def test_invalid_or_unbound_inputs_fail_closed(
    specification: dict,
    index_manifest: dict,
):
    invalid = shard(specification, "agent_trailer_commits", [commit_result()])
    invalid["valid"] = False
    invalid["invalid_reasons"] = ["limit_hit_requires_partition"]
    invalid["limit_hit"] = True
    invalid["result_manifest_sha256"] = result_manifest_sha256(invalid)

    with pytest.raises(EvidencePipelineError, match="invalid query result"):
        build_packet_index(
            specification,
            index_manifest,
            [invalid],
            file_blame_enrichments=[],
        )
    unknown = copy.deepcopy(index_manifest)
    unknown["repositories"] = []
    with pytest.raises(EvidencePipelineError, match="canonical repository"):
        build_packet_index(
            specification,
            unknown,
            [shard(specification, "agent_trailer_commits", [commit_result()])],
            file_blame_enrichments=[],
        )


def test_packet_index_is_deterministic_deduplicated_and_checksummed(
    specification: dict,
    index_manifest: dict,
):
    first_shard = shard(
        specification, "agent_trailer_commits", [commit_result(), commit_result()]
    )
    second_shard = shard(
        specification, "generated_code_disclosure_diffs", [commit_result(diff=True)]
    )

    first = build_packet_index(
        specification,
        index_manifest,
        [second_shard, first_shard],
        file_blame_enrichments=[],
    )
    second = build_packet_index(
        specification,
        index_manifest,
        [first_shard, second_shard],
        file_blame_enrichments=[],
    )

    assert first == second
    assert first["packet_count"] == 2
    assert first["packet_index_sha256"] == packet_index_sha256(first)
    assert validate_packet_index(first, specification) == []
    packet_ids = [packet["packet_id"] for packet in first["packets"]]
    assert len(packet_ids) == len(set(packet_ids))


def test_overlapping_partition_queries_deduplicate_same_result_provenance(
    specification: dict,
    index_manifest: dict,
):
    first_shard = shard(specification, "agent_trailer_commits", [commit_result()])
    overlap_shard = copy.deepcopy(first_shard)
    overlap_shard["rendered_query"] += ' after:"2025-01-01"'
    overlap_shard["rendered_query_sha256"] = hashlib.sha256(
        overlap_shard["rendered_query"].encode()
    ).hexdigest()
    overlap_shard["unit_id"] = discovery_unit_id(overlap_shard)
    overlap_shard["result_manifest_sha256"] = result_manifest_sha256(overlap_shard)

    packet_index = build_packet_index(
        specification,
        index_manifest,
        [overlap_shard, first_shard],
        file_blame_enrichments=[],
    )

    assert packet_index["packet_count"] == 1
    assert packet_index["source_result_manifest_sha256s"] == sorted(
        [
            first_shard["result_manifest_sha256"],
            overlap_shard["result_manifest_sha256"],
        ]
    )
    assert packet_index["packets"][0]["rendered_query_sha256"] == min(
        first_shard["rendered_query_sha256"],
        overlap_shard["rendered_query_sha256"],
    )


def test_packet_index_validator_rejects_malformed_packets_without_crashing(
    specification: dict,
):
    malformed = {
        "packet_index_version": 3,
        "specification_sha256": specification["specification_sha256"],
        "source_result_manifest_sha256s": [],
        "packet_count": 1,
        "pending_file_enrichment_count": 0,
        "sourcegraph_line_number_basis": "zero_based_as_returned_by_graphql",
        "source_url_line_anchor_basis": "one_based",
        "packets": [None],
        "pending_file_enrichments": [],
        "outcomes_consulted": False,
    }
    malformed["packet_index_sha256"] = packet_index_sha256(malformed)

    assert "packets must contain objects" in validate_packet_index(
        malformed, specification
    )


def test_packet_builder_rejects_mutated_frozen_specification(
    specification: dict,
    index_manifest: dict,
):
    changed = copy.deepcopy(specification)
    changed["query_families"][0]["query_template"] += " altered"

    with pytest.raises(
        EvidencePipelineError, match="specification_sha256 does not match"
    ):
        build_packet_index(
            changed,
            index_manifest,
            [],
            file_blame_enrichments=[],
        )


def test_packet_index_and_packets_match_schemas(
    specification: dict,
    index_manifest: dict,
):
    root = Path(__file__).resolve().parents[1]
    result_shard = shard(specification, "ai_ban_policy_files", [file_result()])
    packet_index = build_packet_index(
        specification,
        index_manifest,
        [result_shard],
        file_blame_enrichments=[file_enrichment(result_shard)],
    )
    packet_schema = json.loads(
        (root / "study/sourcegraph-evidence-packet.schema.json").read_text()
    )
    index_schema = json.loads(
        (root / "study/sourcegraph-evidence-packet-index.schema.json").read_text()
    )

    jsonschema.Draft202012Validator(index_schema).validate(packet_index)
    for packet in packet_index["packets"]:
        jsonschema.Draft202012Validator(packet_schema).validate(packet)


def test_file_blame_enrichment_matches_frozen_schema(
    specification: dict,
):
    root = Path(__file__).resolve().parents[1]
    schema = json.loads(
        (root / "study" / "sourcegraph-file-blame-enrichment.schema.json").read_text()
    )
    result_shard = shard(specification, "ai_ban_policy_files", [file_result()])

    jsonschema.Draft202012Validator(schema).validate(file_enrichment(result_shard))


def test_specification_digest_fixture_is_unchanged(specification: dict):
    assert specification["specification_sha256"] == specification_sha256(specification)
