import copy
import hashlib
import json
from pathlib import Path

import jsonschema
import pytest

from authorship.sourcegraph_discovery import evidence_packet_sha256
from authorship.sourcegraph_evidence_pipeline import packet_index_sha256
from authorship.sourcegraph_repository_cases import (
    RepositoryCaseError,
    build_repository_case_index,
    case_index_sha256,
    repository_case_sha256,
    validate_repository_case_index,
    workflow_sha256,
)
from authorship.sourcegraph_repository_cases_cli import main

CUTOFF = "a" * 40


def _packet(
    *,
    packet_id: str,
    repository: str = "org/repo",
    commit_oid: str = "b" * 40,
    observed_at: str = "2025-01-02T00:00:00Z",
    query_family_id: str = "agent_trailer_commits",
    packet_type: str = "adoption_event",
    value: str = "Co-authored-by: Claude <noreply@anthropic.com>",
) -> dict:
    mirror = repository.replace("/", "-")
    rendered_query = (
        f"repo:^github\\.com/sg-evals/{mirror}$@{CUTOFF} "
        f"type:commit {query_family_id} count:all patternType:regexp"
    )
    packet = {
        "packet_version": 3,
        "packet_id": packet_id,
        "packet_type": packet_type,
        "canonical_repository_id": repository,
        "canonical_source_url": f"https://github.com/{repository}",
        "sourcegraph_name": f"github.com/sg-evals/{mirror}",
        "cutoff_commit": CUTOFF,
        "indexed_revision_oid": CUTOFF,
        "query_family_id": query_family_id,
        "rendered_query": rendered_query,
        "rendered_query_sha256": hashlib.sha256(rendered_query.encode()).hexdigest(),
        "sourcegraph_result_ids": [f"sha256:{packet_id}"],
        "candidate_event": {
            "commit_oid": commit_oid,
            "observed_at": observed_at,
        },
        "raw_evidence": [
            {
                "kind": "commit_message",
                "commit_oid": commit_oid,
                "path": None,
                "line": None,
                "value": value,
                "source_url": f"https://github.com/{repository}/commit/{commit_oid}",
            }
        ],
        "outcomes_consulted": False,
    }
    return {**packet, "packet_sha256": evidence_packet_sha256(packet)}


def _packet_index(specification: dict, *packets: dict) -> dict:
    ordered_packets = sorted(
        packets,
        key=lambda packet: (
            packet["candidate_event"]["observed_at"],
            packet["candidate_event"]["commit_oid"],
            packet["canonical_repository_id"],
            packet["packet_type"],
            packet["query_family_id"],
            packet["packet_id"],
        ),
    )
    document = {
        "packet_index_version": 3,
        "specification_sha256": specification["specification_sha256"],
        "source_result_manifest_sha256s": ["c" * 64],
        "packet_count": len(packets),
        "pending_file_enrichment_count": 0,
        "sourcegraph_line_number_basis": "zero_based_as_returned_by_graphql",
        "source_url_line_anchor_basis": "one_based",
        "packets": ordered_packets,
        "pending_file_enrichments": [],
        "outcomes_consulted": False,
    }
    return {**document, "packet_index_sha256": packet_index_sha256(document)}


def _workflow_for_index(workflow: dict, packet_index: dict) -> dict:
    configured = copy.deepcopy(workflow)
    configured["packet_index"]["packet_index_sha256"] = packet_index[
        "packet_index_sha256"
    ]
    configured["packet_index"]["packet_count"] = packet_index["packet_count"]
    configured["workflow_sha256"] = workflow_sha256(configured)
    return configured


@pytest.fixture
def root() -> Path:
    return Path(__file__).resolve().parents[1]


@pytest.fixture
def discovery_specification(root: Path) -> dict:
    return json.loads((root / "study/sourcegraph-discovery.v3.json").read_text())


@pytest.fixture
def workflow_specification(root: Path) -> dict:
    return json.loads(
        (root / "study/sourcegraph-adjudication-workflow.v3.json").read_text()
    )


def _load_cases(output_root: Path, manifest: dict) -> list[dict]:
    return [
        json.loads((output_root / record["case_file"]).read_text())
        for record in manifest["repositories"]
    ]


def test_builds_repository_cases_without_expanding_reviews_per_packet(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
    root: Path,
):
    duplicate_explicit = _packet(
        packet_id="1" * 64,
        query_family_id="agent_trailer_commits",
        commit_oid="b" * 40,
    )
    second_observation = _packet(
        packet_id="2" * 64,
        query_family_id="generated_code_disclosure_diffs",
        commit_oid="b" * 40,
        value="Generated by Claude",
    )
    announcement = _packet(
        packet_id="3" * 64,
        query_family_id="adoption_announcement_files",
        commit_oid="c" * 40,
        observed_at="2024-01-02T00:00:00Z",
        value="We are using an agent",
    )
    policy = _packet(
        packet_id="4" * 64,
        query_family_id="ai_ban_policy_introduction_diffs",
        packet_type="ai_ban_policy",
        commit_oid="d" * 40,
        value="AI-generated contributions are prohibited",
    )
    other_repository = _packet(
        packet_id="5" * 64,
        repository="other/repo",
        query_family_id="recognized_agent_identity_commits",
        commit_oid="e" * 40,
    )
    packet_index = _packet_index(
        discovery_specification,
        duplicate_explicit,
        second_observation,
        announcement,
        policy,
        other_repository,
    )
    workflow_specification = _workflow_for_index(
        workflow_specification,
        packet_index,
    )

    manifest = build_repository_case_index(
        discovery_specification,
        workflow_specification,
        packet_index,
        tmp_path,
    )
    cases = _load_cases(tmp_path, manifest)

    assert manifest["repository_count"] == 2
    assert manifest["event_count"] == 4
    assert manifest["packet_count"] == 5
    assert manifest["review_unit"] == "repository_event"
    assert manifest["packet_level_exhaustive_review_required"] is False
    assert sum(record["packet_count"] for record in manifest["repositories"]) == 5
    assert sum(record["event_count"] for record in manifest["repositories"]) == 4

    primary = next(
        case for case in cases if case["canonical_repository_id"] == "org/repo"
    )
    explicit = primary["queues"]["explicit_provenance_candidates"]
    assert len(explicit) == 1
    assert explicit[0]["packet_ids"] == ["1" * 64, "2" * 64]
    assert explicit[0]["query_family_ids"] == [
        "agent_trailer_commits",
        "generated_code_disclosure_diffs",
    ]
    assert primary["queues"]["adoption_anchor_candidates"] == explicit
    assert [
        event["query_family_ids"]
        for event in primary["queues"]["adoption_challenge_candidates"]
    ] == [["adoption_announcement_files"]]
    assert len(primary["queues"]["ai_ban_candidates"]) == 1
    assert primary["workflow"]["adoption_stop_rule"] == (
        "accept the earliest credible anchor only after resolving every "
        "earlier challenge candidate"
    )
    assert primary["workflow"]["post_adoption_implies_agent"] is False
    assert primary["workflow"]["ambiguous_case_review"] == (
        "two independent reviews plus distinct resolution"
    )

    packet_ids = sorted(
        packet_id
        for case in cases
        for event in case["events"]
        for packet_id in event["packet_ids"]
    )
    assert packet_ids == [str(index) * 64 for index in range(1, 6)]
    assert manifest["case_index_sha256"] == case_index_sha256(manifest)
    for case in cases:
        assert case["repository_case_sha256"] == repository_case_sha256(case)

    index_schema = json.loads(
        (root / "study/sourcegraph-repository-case-index.schema.json").read_text()
    )
    case_schema = json.loads(
        (root / "study/sourcegraph-repository-case.schema.json").read_text()
    )
    jsonschema.Draft202012Validator(index_schema).validate(manifest)
    validator = jsonschema.Draft202012Validator(case_schema)
    for case in cases:
        validator.validate(case)
    assert (
        validate_repository_case_index(
            manifest,
            tmp_path,
            packet_index,
            workflow_specification,
        )
        == []
    )


def test_case_order_is_deterministic_and_workflow_is_outcome_blind(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
):
    later = _packet(
        packet_id="1" * 64,
        observed_at="2025-02-01T00:00:00Z",
        commit_oid="b" * 40,
    )
    earlier = _packet(
        packet_id="2" * 64,
        observed_at="2024-02-01T00:00:00Z",
        commit_oid="c" * 40,
    )
    packet_index = _packet_index(discovery_specification, later, earlier)
    workflow_specification = _workflow_for_index(
        workflow_specification,
        packet_index,
    )

    first = build_repository_case_index(
        discovery_specification,
        workflow_specification,
        packet_index,
        tmp_path,
    )
    second = build_repository_case_index(
        discovery_specification,
        workflow_specification,
        packet_index,
        tmp_path,
    )

    assert second == first
    case = _load_cases(tmp_path, first)[0]
    assert [
        event["candidate_event"]["observed_at"]
        for event in case["queues"]["explicit_provenance_candidates"]
    ] == ["2024-02-01T00:00:00Z", "2025-02-01T00:00:00Z"]
    assert case["outcomes_consulted"] is False

    exposed = copy.deepcopy(packet_index)
    exposed["outcomes_consulted"] = True
    exposed["packet_index_sha256"] = packet_index_sha256(exposed)
    with pytest.raises(RepositoryCaseError, match="outcome blind"):
        build_repository_case_index(
            discovery_specification,
            workflow_specification,
            exposed,
            tmp_path,
        )


def test_validation_detects_tampered_case(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
):
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
    )
    workflow_specification = _workflow_for_index(
        workflow_specification,
        packet_index,
    )
    manifest = build_repository_case_index(
        discovery_specification,
        workflow_specification,
        packet_index,
        tmp_path,
    )
    case_path = tmp_path / manifest["repositories"][0]["case_file"]
    case = json.loads(case_path.read_text())
    case["workflow"]["post_adoption_implies_agent"] = True
    case_path.write_text(json.dumps(case))

    errors = validate_repository_case_index(
        manifest,
        tmp_path,
        packet_index,
        workflow_specification,
    )

    assert "repository case checksum does not match" in errors
    assert "repository case contract is invalid" in errors


@pytest.mark.parametrize(
    ("mutation", "message"),
    [
        (
            lambda workflow: workflow.update(outcomes_consulted=True),
            "outcome blind",
        ),
        (
            lambda workflow: workflow["model_execution"].update(paid_batch_api=True),
            "forbid paid Batch API",
        ),
        (
            lambda workflow: workflow["review_design"].update(review_unit="packet"),
            "review unit",
        ),
        (
            lambda workflow: workflow["discovery_specification"].update(
                specification_sha256="f" * 64
            ),
            "discovery specification",
        ),
    ],
)
def test_builder_rejects_invalid_workflow_contract(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
    mutation,
    message: str,
):
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
    )
    workflow = _workflow_for_index(workflow_specification, packet_index)
    mutation(workflow)
    workflow["workflow_sha256"] = workflow_sha256(workflow)

    with pytest.raises(RepositoryCaseError, match=message):
        build_repository_case_index(
            discovery_specification,
            workflow,
            packet_index,
            tmp_path,
        )


def test_builder_rejects_checksum_and_packet_binding_drift(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
):
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
    )
    workflow = _workflow_for_index(workflow_specification, packet_index)
    broken_workflow = copy.deepcopy(workflow)
    broken_workflow["workflow_sha256"] = "f" * 64
    with pytest.raises(RepositoryCaseError, match="workflow specification checksum"):
        build_repository_case_index(
            discovery_specification,
            broken_workflow,
            packet_index,
            tmp_path,
        )

    wrong_checksum = copy.deepcopy(workflow)
    wrong_checksum["packet_index"]["packet_index_sha256"] = "f" * 64
    wrong_checksum["workflow_sha256"] = workflow_sha256(wrong_checksum)
    with pytest.raises(RepositoryCaseError, match="packet index checksum"):
        build_repository_case_index(
            discovery_specification,
            wrong_checksum,
            packet_index,
            tmp_path,
        )

    wrong_count = copy.deepcopy(workflow)
    wrong_count["packet_index"]["packet_count"] = 2
    wrong_count["workflow_sha256"] = workflow_sha256(wrong_count)
    with pytest.raises(RepositoryCaseError, match="packet count"):
        build_repository_case_index(
            discovery_specification,
            wrong_count,
            packet_index,
            tmp_path,
        )

    tampered_index = copy.deepcopy(packet_index)
    tampered_index["packet_count"] = 2
    with pytest.raises(RepositoryCaseError, match="packet index is invalid"):
        build_repository_case_index(
            discovery_specification,
            workflow,
            tampered_index,
            tmp_path,
        )


def test_validator_reports_missing_case_and_manifest_drift(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
):
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
    )
    workflow = _workflow_for_index(workflow_specification, packet_index)
    manifest = build_repository_case_index(
        discovery_specification,
        workflow,
        packet_index,
        tmp_path,
    )
    missing_path = tmp_path / manifest["repositories"][0]["case_file"]
    missing_path.unlink()
    changed = copy.deepcopy(manifest)
    changed["packet_count"] = 2

    errors = validate_repository_case_index(
        changed,
        tmp_path,
        packet_index,
        workflow,
    )

    assert "case index checksum does not match" in errors
    assert "repository case file is missing" in errors
    assert "packet count does not match" in errors


def test_locked_protocol_amendment_and_workflow_validate(root: Path):
    amendment = json.loads((root / "study/protocol-amendment.v3.1.json").read_text())
    amendment_schema = json.loads(
        (root / "study/protocol-amendment-v3.1.schema.json").read_text()
    )
    workflow = json.loads(
        (root / "study/sourcegraph-adjudication-workflow.v3.json").read_text()
    )
    workflow_schema = json.loads(
        (root / "study/sourcegraph-adjudication-workflow.schema.json").read_text()
    )

    jsonschema.Draft202012Validator(amendment_schema).validate(amendment)
    jsonschema.Draft202012Validator(workflow_schema).validate(workflow)
    assert amendment["primary_question"].startswith(
        "Does explicitly agent-attributed code survive differently"
    )
    assert amendment["exposure"]["primary_definition"] == "explicit_provenance"
    assert amendment["survival"]["primary_event"] == (
        "first_modification_or_deletion_of_introduced_line"
    )
    assert amendment["human_comparator"]["primary"] == (
        "same_repository_contemporary_pre_adoption_human_commits"
    )
    assert amendment["claims"]["causal"] is False
    assert amendment["ai_ban_repositories"]["primary_role"] == "negative_control"
    assert workflow["review_design"]["packet_level_exhaustive_review"] is False
    assert workflow["model_execution"]["paid_batch_api"] is False


def test_cli_writes_valid_manifest(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
):
    pytest.importorskip("ijson")
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
    )
    workflow = _workflow_for_index(workflow_specification, packet_index)
    discovery_path = tmp_path / "discovery.json"
    workflow_path = tmp_path / "workflow.json"
    packet_path = tmp_path / "packets.json"
    output_root = tmp_path / "cases"
    manifest_path = tmp_path / "case-index.json"
    discovery_path.write_text(json.dumps(discovery_specification))
    workflow_path.write_text(json.dumps(workflow))
    packet_path.write_text(json.dumps(packet_index))

    exit_code = main(
        [
            "--discovery-specification",
            str(discovery_path),
            "--workflow-specification",
            str(workflow_path),
            "--packet-index",
            str(packet_path),
            "--output-root",
            str(output_root),
            "--manifest-output",
            str(manifest_path),
        ]
    )

    assert exit_code == 0
    manifest = json.loads(manifest_path.read_text())
    assert (
        validate_repository_case_index(
            manifest,
            output_root,
            packet_index,
            workflow,
        )
        == []
    )


def test_validator_rejects_self_consistent_packet_omission(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
):
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
        _packet(packet_id="2" * 64, repository="other/repo"),
    )
    workflow = _workflow_for_index(workflow_specification, packet_index)
    manifest = build_repository_case_index(
        discovery_specification,
        workflow,
        packet_index,
        tmp_path,
    )
    omitted = copy.deepcopy(manifest)
    omitted["repositories"] = omitted["repositories"][0:1]
    omitted["repository_count"] = 1
    omitted["event_count"] = omitted["repositories"][0]["event_count"]
    omitted["packet_count"] = omitted["repositories"][0]["packet_count"]
    omitted["case_index_sha256"] = case_index_sha256(omitted)

    errors = validate_repository_case_index(
        omitted,
        tmp_path,
        packet_index,
        workflow,
    )

    assert "case packet IDs do not equal frozen packet index" in errors


def test_validator_rejects_self_consistent_event_metadata_drift(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
):
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
    )
    workflow = _workflow_for_index(workflow_specification, packet_index)
    manifest = build_repository_case_index(
        discovery_specification,
        workflow,
        packet_index,
        tmp_path,
    )
    changed = copy.deepcopy(manifest)
    record = changed["repositories"][0]
    case_path = tmp_path / record["case_file"]
    case = json.loads(case_path.read_text())
    event_id = case["events"][0]["event_id"]
    for event in case["events"]:
        if event["event_id"] == event_id:
            event["candidate_event"]["observed_at"] = "1999-01-01T00:00:00Z"
    for queue in case["queues"].values():
        for event in queue:
            if event["event_id"] == event_id:
                event["candidate_event"]["observed_at"] = "1999-01-01T00:00:00Z"
    case["repository_case_sha256"] = repository_case_sha256(case)
    payload = (
        json.dumps(case, ensure_ascii=False, separators=(",", ":"), sort_keys=True)
        + "\n"
    ).encode()
    case_path.write_bytes(payload)
    record["byte_count"] = len(payload)
    record["sha256"] = hashlib.sha256(payload).hexdigest()
    changed["case_index_sha256"] = case_index_sha256(changed)

    errors = validate_repository_case_index(
        changed,
        tmp_path,
        packet_index,
        workflow,
    )

    assert "repository case differs from frozen packet evidence" in errors


def test_validator_rejects_tampered_workflow_policy(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
):
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
    )
    workflow = _workflow_for_index(workflow_specification, packet_index)
    manifest = build_repository_case_index(
        discovery_specification,
        workflow,
        packet_index,
        tmp_path,
    )
    tampered = copy.deepcopy(workflow)
    tampered["model_execution"]["paid_batch_api"] = True
    tampered["workflow_sha256"] = workflow_sha256(tampered)

    errors = validate_repository_case_index(
        manifest,
        tmp_path,
        packet_index,
        tampered,
    )

    assert "workflow must forbid paid Batch API execution" in errors
    assert "case index workflow binding does not match" in errors


@pytest.mark.parametrize(
    ("mutation", "message"),
    [
        (
            lambda workflow: workflow["model_execution"].update(paid_batch_api=True),
            "forbid paid Batch API",
        ),
        (
            lambda workflow: workflow["model_execution"].update(
                user_openai_api_key=True
            ),
            "forbid user OpenAI API keys",
        ),
        (
            lambda workflow: workflow["model_execution"].update(
                local_or_subagent_review=False
            ),
            "require local or subagent review",
        ),
        (
            lambda workflow: workflow["model_execution"].update(
                semantic_decisions_delegated_to_reviewers=False
            ),
            "delegate semantic decisions to reviewers",
        ),
        (
            lambda workflow: workflow["review_design"].update(
                packet_level_exhaustive_review=True
            ),
            "not require exhaustive packet review",
        ),
        (
            lambda workflow: workflow["review_design"].update(
                post_adoption_implies_agent=True
            ),
            "not infer agent authorship",
        ),
    ],
)
def test_streaming_builder_rejects_tampered_workflow_policy(
    discovery_specification: dict,
    workflow_specification: dict,
    tmp_path: Path,
    mutation,
    message: str,
):
    pytest.importorskip("ijson")
    packet_index = _packet_index(
        discovery_specification,
        _packet(packet_id="1" * 64),
    )
    workflow = _workflow_for_index(workflow_specification, packet_index)
    mutation(workflow)
    workflow["workflow_sha256"] = workflow_sha256(workflow)
    discovery_path = tmp_path / "discovery.json"
    workflow_path = tmp_path / "workflow.json"
    packet_path = tmp_path / "packets.json"
    discovery_path.write_text(json.dumps(discovery_specification))
    workflow_path.write_text(json.dumps(workflow))
    packet_path.write_text(json.dumps(packet_index))

    with pytest.raises(RepositoryCaseError, match=message):
        main(
            [
                "--discovery-specification",
                str(discovery_path),
                "--workflow-specification",
                str(workflow_path),
                "--packet-index",
                str(packet_path),
                "--output-root",
                str(tmp_path / "cases"),
                "--manifest-output",
                str(tmp_path / "case-index.json"),
            ]
        )


@pytest.mark.parametrize("payload", ["[]", "{not-json"])
def test_cli_rejects_invalid_input_mapping(tmp_path: Path, payload: str):
    invalid_path = tmp_path / "invalid.json"
    invalid_path.write_text(payload)

    with pytest.raises(RepositoryCaseError, match="must contain|cannot read"):
        main(["--discovery-specification", str(invalid_path)])
