import hashlib
import json
import os
from datetime import datetime, timezone
from pathlib import Path
from threading import Event, Lock

import pytest
import jsonschema

from authorship.sourcegraph_discovery_execution import (
    discovery_unit_id,
    render_query,
    result_manifest_sha256,
)
from authorship.sourcegraph_discovery_partition import (
    build_partition_plan,
    build_query_branch_refined_partition_plan,
    build_refined_partition_plan,
    execute_partition_plan,
    execute_query_branch_refined_partition_plan,
    execute_refined_partition_plan,
    partition_execution_sha256,
    partition_plan_sha256,
    validate_partition_execution,
)

SHA_A = "a" * 40
SOURCEGRAPH_NAME = "github.com/sg-evals/org-repo"
EXECUTED_AT = datetime(2026, 7, 28, 12, tzinfo=timezone.utc)


@pytest.fixture
def specification() -> dict:
    path = Path(__file__).resolve().parents[1] / "study/sourcegraph-discovery.v3.json"
    return json.loads(path.read_text())


def timed_out_parent(
    specification: dict,
    family_id: str = "generated_code_disclosure_diffs",
) -> dict:
    family = next(
        family
        for family in specification["query_families"]
        if family["id"] == family_id
    )
    rendered_query = render_query(family, SOURCEGRAPH_NAME, SHA_A)
    document = {
        "result_manifest_version": 3,
        "query_family_id": family["id"],
        "result_type": family["result_type"],
        "canonical_repository_id": "org/repo",
        "sourcegraph_name": SOURCEGRAPH_NAME,
        "cutoff_commit": SHA_A,
        "rendered_query": rendered_query,
        "rendered_query_sha256": hashlib.sha256(rendered_query.encode()).hexdigest(),
        "executed_at": "2026-07-28T00:00:00Z",
        "sourcegraph_result_ids": [],
        "result_count": 0,
        "result_object_count": 0,
        "limit_hit": False,
        "cloning_repositories": [],
        "missing_repositories": [],
        "timed_out_repositories": [SOURCEGRAPH_NAME],
        "valid": False,
        "invalid_reasons": ["timed_out_repositories"],
        "raw_results": [],
        "outcomes_consulted": False,
    }
    document["unit_id"] = discovery_unit_id(document)
    return {
        **document,
        "result_manifest_sha256": result_manifest_sha256(document),
    }


def empty_response() -> dict:
    return {
        "results": [],
        "result_count": 0,
        "limit_hit": False,
        "cloning_repositories": [],
        "missing_repositories": [],
        "timed_out_repositories": [],
    }


def commit_result() -> dict:
    return {
        "__typename": "CommitSearchResult",
        "messagePreview": {"value": "Generated by agent", "highlights": []},
        "diffPreview": {"value": "+ generated by agent"},
        "commit": {
            "repository": {"name": SOURCEGRAPH_NAME},
            "oid": "c" * 40,
            "url": "/repo/-/commit/" + "c" * 40,
            "subject": "Generated by agent",
            "author": {
                "date": "2024-01-01T12:00:00Z",
                "person": {"displayName": "Example"},
            },
        },
    }


def test_partition_plan_is_deterministic_complete_and_checksummed(
    specification: dict,
):
    plan = build_partition_plan(specification, [timed_out_parent(specification)])
    schema_path = (
        Path(__file__).resolve().parents[1]
        / "study/sourcegraph-discovery-partition-plan.schema.json"
    )

    assert plan["status"] == "frozen_before_partition_execution"
    assert plan["parent_count"] == 1
    assert (
        plan["strategy"]
        == "fixed_14_day_windows_5m_timeout_with_one_day_boundary_overlap"
    )
    assert plan["child_unit_count"] == 93
    assert plan["partition_plan_sha256"] == partition_plan_sha256(plan)
    parent = plan["parents"][0]
    assert (
        parent["parent_result_manifest_sha256"]
        == timed_out_parent(specification)["result_manifest_sha256"]
    )
    assert parent["coverage_start_exclusive"] == "2023-01-01"
    assert parent["coverage_end_exclusive"] == "2026-07-25"
    assert parent["boundary_overlap_days"] == 1
    assert parent["deduplication_key"] == "sourcegraph_result_id"
    children = parent["children"]
    assert all("timeout:5m" in child["unit"]["rendered_query"] for child in children)
    assert not any(
        "timeout:1m" in child["unit"]["rendered_query"] for child in children
    )
    assert children[0]["after_exclusive"] == "2023-01-01"
    assert children[-1]["before_exclusive"] == "2026-07-25"
    for left, right in zip(children, children[1:]):
        assert left["before_exclusive"] > right["after_exclusive"]
    assert len({child["unit"]["unit_id"] for child in children}) == 93
    jsonschema.Draft202012Validator(json.loads(schema_path.read_text())).validate(plan)


def test_partition_plan_rejects_non_timeout_or_non_history_parent(
    specification: dict,
):
    parent = timed_out_parent(specification)
    parent["timed_out_repositories"] = []
    parent["invalid_reasons"] = []
    parent["valid"] = True
    parent["result_manifest_sha256"] = result_manifest_sha256(parent)

    with pytest.raises(ValueError, match="timed-out"):
        build_partition_plan(specification, [parent])

    parent = timed_out_parent(specification)
    parent["result_type"] = "file"
    parent["result_manifest_sha256"] = result_manifest_sha256(parent)
    with pytest.raises(ValueError, match="commit or diff"):
        build_partition_plan(specification, [parent])


def test_partition_plan_requires_timeout_evidence_for_parent_repository(
    specification: dict,
):
    parent = timed_out_parent(specification)
    parent["timed_out_repositories"] = ["github.com/sg-evals/another-repo"]
    parent["result_manifest_sha256"] = result_manifest_sha256(parent)

    with pytest.raises(ValueError, match="parent repository"):
        build_partition_plan(specification, [parent])


def test_partition_plan_rejects_timeout_with_an_unresolved_second_failure(
    specification: dict,
):
    parent = timed_out_parent(specification)
    parent["invalid_reasons"] = [
        "missing_repositories",
        "timed_out_repositories",
    ]
    parent["missing_repositories"] = [SOURCEGRAPH_NAME]
    parent["result_manifest_sha256"] = result_manifest_sha256(parent)

    with pytest.raises(ValueError, match="timed-out"):
        build_partition_plan(specification, [parent])


@pytest.mark.parametrize("mutation", ["query", "unit_id"])
def test_partition_plan_requires_the_exact_frozen_parent_unit(
    specification: dict, mutation: str
):
    parent = timed_out_parent(specification)
    if mutation == "query":
        parent["rendered_query"] = parent["rendered_query"].replace(
            "(generated|authored|implemented)", "NEVER_MATCH_THIS_TOKEN"
        )
        parent["rendered_query_sha256"] = hashlib.sha256(
            parent["rendered_query"].encode()
        ).hexdigest()
    else:
        parent["unit_id"] = "d" * 64
    parent["result_manifest_sha256"] = result_manifest_sha256(parent)

    with pytest.raises(ValueError, match="frozen query unit"):
        build_partition_plan(specification, [parent])


def test_partition_execution_is_atomic_resumable_and_checksummed(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    calls = []

    def runner(query: str, *_args: str) -> dict:
        calls.append(query)
        return empty_response()

    first = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=runner,
        clock=lambda: EXECUTED_AT,
    )
    schema_path = (
        Path(__file__).resolve().parents[1]
        / "study/sourcegraph-discovery-partition-execution.schema.json"
    )
    second = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=runner,
        clock=lambda: EXECUTED_AT,
    )

    assert first["status"] == "complete"
    assert first["valid_parent_count"] == 1
    assert first["partition_execution_sha256"] == partition_execution_sha256(first)
    assert "executed_child_unit_count" not in first
    assert "reused_child_unit_count" not in second
    assert all(
        "reused" not in child
        for parent_summary in second["parents"]
        for child in parent_summary["children"]
    )
    assert len(calls) == 93
    assert (tmp_path / "sourcegraph-discovery-partition-execution.v3.json").is_file()
    assert list(tmp_path.rglob("*.tmp")) == []
    jsonschema.Draft202012Validator(json.loads(schema_path.read_text())).validate(first)
    assert (
        validate_partition_execution(
            first,
            plan,
            specification,
            tmp_path,
            source_parents=[parent],
        )
        == []
    )
    for child in first["parents"][0]["children"]:
        assert (tmp_path / child["shard_path"]).is_file()


def test_partition_execution_runs_independent_children_with_bounded_parallelism(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    release = Event()
    lock = Lock()
    active = 0
    peak = 0

    def runner(*_args: str) -> dict:
        nonlocal active, peak
        with lock:
            active += 1
            peak = max(peak, active)
            if peak == 2:
                release.set()
        assert release.wait(timeout=1)
        with lock:
            active -= 1
        return empty_response()

    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=runner,
        clock=lambda: EXECUTED_AT,
        max_workers=2,
    )

    assert execution["status"] == "complete"
    assert peak == 2


def test_partition_execution_fails_closed_on_child_timeout(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    response = empty_response()
    response["timed_out_repositories"] = [SOURCEGRAPH_NAME]

    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: response,
        clock=lambda: EXECUTED_AT,
    )

    assert execution["status"] == "incomplete"
    assert execution["invalid_parent_count"] == 1
    assert execution["parents"][0]["invalid_reasons"] == ["invalid_child_unit"]
    assert (
        validate_partition_execution(
            execution,
            plan,
            specification,
            tmp_path,
            source_parents=[parent],
            allow_timed_out_children=True,
        )
        == []
    )
    assert validate_partition_execution(
        execution,
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
    )
    resumed = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: (_ for _ in ()).throw(
            AssertionError("validated timeout shard should be reused")
        ),
        clock=lambda: EXECUTED_AT,
    )
    assert resumed["parents"][0]["children"][0]["invalid_reasons"] == [
        "timed_out_repositories"
    ]


def test_refined_plan_replaces_only_timed_out_children_with_daily_windows(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    response = empty_response()
    response["timed_out_repositories"] = [SOURCEGRAPH_NAME]
    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: response,
        clock=lambda: EXECUTED_AT,
    )

    refined = build_refined_partition_plan(
        specification,
        plan,
        execution,
        tmp_path,
        source_parents=[parent],
    )

    assert refined["strategy"] == "failed_14_day_windows_refined_to_1_day"
    assert refined["refinement_source_plan_sha256"] == plan["partition_plan_sha256"]
    assert (
        refined["refinement_source_execution_sha256"]
        == execution["partition_execution_sha256"]
    )
    assert refined["child_unit_count"] > plan["child_unit_count"]
    assert all(
        "timeout:5m" in child["unit"]["rendered_query"]
        for child in refined["parents"][0]["children"]
    )
    schema_path = (
        Path(__file__).resolve().parents[1]
        / "study/sourcegraph-discovery-partition-plan.schema.json"
    )
    jsonschema.Draft202012Validator(json.loads(schema_path.read_text())).validate(
        refined
    )
    calls = 0
    call_lock = Lock()

    def runner(*_args: str) -> dict:
        nonlocal calls
        with call_lock:
            calls += 1
        return empty_response()

    final = execute_refined_partition_plan(
        refined,
        specification,
        tmp_path,
        source_plan=plan,
        source_execution=execution,
        source_parents=[parent],
        query_runner=runner,
        clock=lambda: EXECUTED_AT,
    )

    assert final["status"] == "complete"
    assert calls == refined["child_unit_count"]
    assert (
        validate_partition_execution(
            final,
            refined,
            specification,
            tmp_path,
            source_parents=[parent],
            expected_plan=refined,
        )
        == []
    )


def test_branch_refinement_replaces_failed_daily_ai_ban_leaf(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification, "ai_ban_policy_introduction_diffs")
    root_plan = build_partition_plan(specification, [parent])
    timeout = empty_response()
    timeout["timed_out_repositories"] = [SOURCEGRAPH_NAME]
    root_execution = execute_partition_plan(
        root_plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: timeout,
        clock=lambda: EXECUTED_AT,
    )
    daily_plan = build_refined_partition_plan(
        specification,
        root_plan,
        root_execution,
        tmp_path,
        source_parents=[parent],
    )

    def daily_runner(query: str, *_args: str) -> dict:
        return timeout if 'after:"2023-01-01"' in query else empty_response()

    daily_execution = execute_refined_partition_plan(
        daily_plan,
        specification,
        tmp_path,
        source_plan=root_plan,
        source_execution=root_execution,
        source_parents=[parent],
        query_runner=daily_runner,
        clock=lambda: EXECUTED_AT,
    )
    branch_plan = build_query_branch_refined_partition_plan(
        specification,
        daily_plan,
        daily_execution,
        tmp_path,
        source_parents=[parent],
        ancestor_plan=root_plan,
        ancestor_execution=root_execution,
    )

    assert (
        branch_plan["strategy"]
        == "failed_daily_ai_ban_windows_refined_by_filename_policy_and_term"
    )
    failed_daily_children = sum(
        not child["valid"]
        for parent_summary in daily_execution["parents"]
        for child in parent_summary["children"]
    )
    assert (
        branch_plan["child_unit_count"]
        == daily_plan["child_unit_count"] + 125 * failed_daily_children
    )
    assert any(
        "file:(^|/)README(\\.[^/]*)?$" in child["unit"]["rendered_query"]
        and "AI.{0,240}prohibit" in child["unit"]["rendered_query"]
        for parent_plan in branch_plan["parents"]
        for child in parent_plan["children"]
    )
    final = execute_query_branch_refined_partition_plan(
        branch_plan,
        specification,
        tmp_path,
        source_plan=daily_plan,
        source_execution=daily_execution,
        source_parents=[parent],
        ancestor_plan=root_plan,
        ancestor_execution=root_execution,
        query_runner=lambda *_args: empty_response(),
        clock=lambda: EXECUTED_AT,
    )
    assert final["status"] == "complete"
    assert (
        validate_partition_execution(
            final,
            branch_plan,
            specification,
            tmp_path,
            source_parents=[parent],
            expected_plan=branch_plan,
        )
        == []
    )


def test_partition_execution_deduplicates_results_across_overlap_windows(
    tmp_path: Path,
    specification: dict,
):
    parent_source = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent_source])
    response = empty_response()
    response.update({"results": [commit_result()], "result_count": 1})

    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent_source],
        query_runner=lambda *_args: response,
        clock=lambda: EXECUTED_AT,
    )

    parent = execution["parents"][0]
    assert execution["status"] == "complete"
    assert parent["invalid_reasons"] == []
    assert len(parent["duplicate_result_ids"]) == 1
    assert parent["duplicate_result_count"] == 1
    assert parent["deduplicated_result_count"] == 1


def test_partition_execution_rejects_mutated_plan(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    plan["parents"][0]["children"][0]["before_exclusive"] = "2024-02-01"

    with pytest.raises(ValueError, match="plan SHA-256"):
        execute_partition_plan(
            plan,
            specification,
            tmp_path,
            source_parents=[parent],
            query_runner=lambda *_args: empty_response(),
            clock=lambda: EXECUTED_AT,
        )


def test_partition_execution_rejects_rechecksummed_semantic_mutation(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    plan["parents"][0]["children"][0]["before_exclusive"] = "2024-02-01"
    plan["partition_plan_sha256"] = partition_plan_sha256(plan)

    with pytest.raises(ValueError, match="semantics"):
        execute_partition_plan(
            plan,
            specification,
            tmp_path,
            source_parents=[parent],
            query_runner=lambda *_args: empty_response(),
            clock=lambda: EXECUTED_AT,
        )


def test_partition_execution_anchors_children_to_source_parent(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    changed = plan["parents"][0]
    changed["children"][0]["unit"][
        "sourcegraph_name"
    ] = "github.com/attacker/other-repo"
    plan["partition_plan_sha256"] = partition_plan_sha256(plan)

    with pytest.raises(ValueError, match="source parent manifests"):
        execute_partition_plan(
            plan,
            specification,
            tmp_path,
            source_parents=[parent],
            query_runner=lambda *_args: empty_response(),
            clock=lambda: EXECUTED_AT,
        )


def test_partition_execution_rejects_rechecksummed_duplicate_parent(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    plan["parents"].append(json.loads(json.dumps(plan["parents"][0])))
    plan["parent_count"] = 2
    plan["child_unit_count"] = 186
    plan["partition_plan_sha256"] = partition_plan_sha256(plan)

    with pytest.raises(ValueError, match="source parent manifests"):
        execute_partition_plan(
            plan,
            specification,
            tmp_path,
            source_parents=[parent],
            query_runner=lambda *_args: empty_response(),
            clock=lambda: EXECUTED_AT,
        )


def test_partition_execution_uses_validated_snapshot_during_queries(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    queries = []

    def mutating_runner(query: str, *_args: str) -> dict:
        queries.append(query)
        if len(queries) == 1:
            changed = plan["parents"][0]["children"][1]["unit"]
            changed["rendered_query"] = changed["rendered_query"].replace(
                "github\\.com/sg-evals/org-repo",
                "github\\.com/attacker/other-repo",
            )
            plan["parents"].append(json.loads(json.dumps(plan["parents"][0])))
        return empty_response()

    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=mutating_runner,
        clock=lambda: EXECUTED_AT,
    )

    assert execution["parent_count"] == 1
    assert len(queries) == 93
    assert not any("attacker" in query for query in queries)


def test_partition_execution_validator_rejects_rechecksummed_child_redirection(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: empty_response(),
        clock=lambda: EXECUTED_AT,
    )
    execution["parents"][0]["children"][0]["shard_path"] = "../outside.json"
    execution["partition_execution_sha256"] = partition_execution_sha256(execution)

    errors = validate_partition_execution(
        execution,
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
    )

    assert any("child shard path" in error for error in errors)


@pytest.mark.parametrize(
    ("field", "value"),
    [
        ("partition_execution_version", 4),
        ("status", "incomplete"),
        ("outcomes_consulted", True),
    ],
)
def test_partition_execution_validator_rejects_invalid_contract_fields(
    tmp_path: Path,
    specification: dict,
    field: str,
    value: object,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: empty_response(),
        clock=lambda: EXECUTED_AT,
    )
    execution[field] = value
    execution["partition_execution_sha256"] = partition_execution_sha256(execution)

    errors = validate_partition_execution(
        execution,
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
    )

    assert errors


def test_partition_execution_validator_rejects_unverifiable_reuse_claim(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: empty_response(),
        clock=lambda: EXECUTED_AT,
    )
    execution["parents"][0]["children"][0]["reused"] = True
    execution["partition_execution_sha256"] = partition_execution_sha256(execution)

    errors = validate_partition_execution(
        execution,
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
    )

    assert any("unexpected fields" in error for error in errors)


@pytest.mark.parametrize("corruption", ["invalid_utf8", "unhashable_result_id"])
def test_partition_execution_validator_reports_malformed_child_without_raising(
    tmp_path: Path,
    specification: dict,
    corruption: str,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: empty_response(),
        clock=lambda: EXECUTED_AT,
    )
    child = execution["parents"][0]["children"][0]
    shard_path = tmp_path / child["shard_path"]
    if corruption == "invalid_utf8":
        shard_path.write_bytes(b"\xff")
    else:
        shard = json.loads(shard_path.read_text())
        shard["sourcegraph_result_ids"] = [{}]
        shard["result_manifest_sha256"] = result_manifest_sha256(shard)
        shard_path.write_text(json.dumps(shard))
        child["sourcegraph_result_ids"] = [{}]
        child["result_manifest_sha256"] = shard["result_manifest_sha256"]
        execution["partition_execution_sha256"] = partition_execution_sha256(execution)

    errors = validate_partition_execution(
        execution,
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
    )

    assert errors


def test_partition_execution_validator_rejects_child_symlink_outside_root(
    tmp_path: Path,
    specification: dict,
):
    parent = timed_out_parent(specification)
    plan = build_partition_plan(specification, [parent])
    execution = execute_partition_plan(
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
        query_runner=lambda *_args: empty_response(),
        clock=lambda: EXECUTED_AT,
    )
    shard_path = tmp_path / execution["parents"][0]["children"][0]["shard_path"]
    outside = tmp_path.parent / "outside-partition-shard.json"
    outside.write_bytes(shard_path.read_bytes())
    shard_path.unlink()
    os.symlink(outside, shard_path)

    errors = validate_partition_execution(
        execution,
        plan,
        specification,
        tmp_path,
        source_parents=[parent],
    )

    assert any("outside output directory" in error for error in errors)
